### ISSUE TITLE
New BSIP: TOKEN STREAM transfer type

### ISSUE THREAD

**Issue by OpenLedgerApp** [bitshares/bsips#128]
## Motivation
For specific services there might be a need to have a regularly paid transfer: daily, hourly or weekly. A good example would be running a worker for BitShares. 
A similar mechanism could be useful for helping services with automatic regular payments.

## Abstract
A new type of a transfer transaction - token stream is created - to transfer certain amount of an asset for a specified period of time. 
The following parameters can be specified:
- Total amount
- Transfer duration (seconds) 
or 
Transfer speed (amount/second)
- Transfer frequency (seconds between transfers)

The Sender can pause or cancel the stream at any time. 
The of Receiver the transaction can cancel the stream at any time as well.

Both Sender and Receiver can see a list of all active streams in their UI.

**Example**:
```
A stream of 1000 "Super" assets is configured from account Sender to account Receiver:

Transfer duration: 10 days (864 000 seconds)
Transfer speed is calculated as 0.00115 assets per second.
Transfer frequency is specified as 1 hour (3600 seconds)
After signing of the transaction, 
1000 Super tokens will be frozen on the Sender account, 
4.166 Super assets will be sent from Sender to Receiver each hour.
```
This shall be similar to worker functionality, but applied to a specific account and potentially utilized with a higher frequency (workers are paid daily, the token stream should be done hourly or even more frequent).

Please let us know your thoughts,
OpenLedger team

**Comment by cogutvalera** [comment]
this can be implemented as 3rd party app

**Comment by cogutvalera** [comment]
I've got answer on my own question in this comment of @jmjatlanta  https://github.com/bitshares/bsips/issues/126#issuecomment-441713299

**Comment by abitmore** [comment]
I think the withdraw_permission operations can already serve most of functionalities described in this issue. BTW automated recurrent transfer is expensive so we should think about how to discourage abuse (e.g. high fee) in advance if want to implement such a feature.

**Comment by OpenLedgerApp** [comment]
thanks, @abitmore. I can see quite a lot of different discussion going on withdraw_permission.
We will look into this.

**Comment by OpenLedgerApp** [comment]
It turns out that most of the suggested functionality is already implemented in core. 
The original idea was described here: 
https://github.com/bitshares/bitshares-core/issues/540
There are great use cases done by @TheTaconator  here : 
https://github.com/TheTaconator/bsips/blob/bsip42-draft/bsip-0042.md
And the UI is in the works for this feature:
https://github.com/bitshares/bitshares-ui/issues/30
So,  I am closing the issue.
