### ISSUE TITLE
New BSIP: User custom price for his margin call order

### ISSUE THREAD

**Issue by code-maggot** [bitshares/bsips#129]
Abstract
A use is able to repay debt by place order to sell his collateral manually. Of course, price should less than Margin Call Price but more than BG price.

Bitshares UI is to be updated to give the function.

Motivation
Currently, there is no active way to close out for those whose CR < 175%. He can only hope feed price rise or margin call order be eaten if he has no extra money. While sometimes market keeps going down and no one want to eat call orders, those can only watch their CR lower and lower eventually get nothing back. If user can manually place a sell order to sell his collateral, risk of black swan will be reduced and it's also a better UX.

Any thoughts?

**Comment by abitmore** [comment]
Make sense. Actually an approach is to make the global MSSR optional for debt owners, or give them abilities to specify their own MSSR.

**Comment by code-maggot** [comment]
> Make sense. Actually an approach is to make the global MSSR optional for debt owners, or give them abilities to specify their own MSSR.

Yep. For this MSSR way, since user may have several margin position, they might like to set seperate MSSR for different bitAsset.

**Comment by clockworkgr** [comment]
Can't really see debt owners being prudent with that.,...theyre more likely to set it to the minimum, judging by how they treat their CR.

**Comment by code-maggot** [comment]
> Can't really see debt owners being prudent with that.,...theyre more likely to set it to the minimum, judging by how they treat their CR.
For those fully invested and wake up found their CR already below 175%(which often happens), they just can do nothing to protect their coins. This BSIP is designed for those people, give them functionality to close their position when call order wouldnt be eaten. Without that, how can they show their prudence?

**Comment by bitcrab** [comment]
why only for margin call orders? why not to provide a general feature that trader can place orders to sell the collateral to reduce the debt, for both margin called and non-margin called positions?

**Comment by code-maggot** [comment]
> why only for margin call orders? why not to provide a general feature that trader can place orders to sell the collateral to reduce the debt, for both margin called and non-margin called positions?

I came out with this idea in order to reduce the debt when margin called.  Sure it's better make this as a general feature.

**Comment by pmconrad** [comment]
IMO this provides very little value since manual trading can achieve more or less the same, given only a small amount of starting capital.

**Comment by shulthz** [comment]
I think the asset owner can set the Margin Call Ratio.

Seperate the Margin Call Ratio and the Maintenance collateral ratio.

e.g. if the Maintenance collateral ratio is 1.75, system can set the basic Margin Call Ratio to 1.6, and the asset owner can set his Margin Call Ratio from 1.6 to 1.35.

When the price drop down 8.5%, the margin call could only happen at 1.6, as the Market Rebounds always, this provides the market with a large buffer as prices fall again.

**Comment by abitmore** [comment]
Please continue the discussion in https://github.com/bitshares/bsips/issues/156, closing this one.

**Comment by abitmore** [comment]
See PR https://github.com/bitshares/bsips/pull/211 (BSIP62).
