### ISSUE TITLE
bsip#16: Optimization to Force Settlement Parameters of BitCNY

### ISSUE THREAD

**Issue by bitcrab** [bitshares/bsips#13]
```
BSIP: 0016
Title: Optimization to Force Settlement Parameters of BitCNY
Authors: Jerry Liu<jerry.liu@transwiser.com>
Status: Draft
Type: Protocol
Created: 2016-05-06
Discussion: https://bitsharestalk.org/index.php/topic,22355.0.html
Worker: no
```
# Abstract

By optimizing 2 key force settlement parameters of bitCNY to make the force settlement rule more reasonable, the expected consequence is that the shorters will be encouraged to provide more bitCNY supply and benefit the whole economy.
# Motivation

As a smartcoin, bitCNY pegs to CNY, it is expected to be used in some payment and trading scenarios as a stable currency, however, as bitCNY is generated by shorting with BTS as collateral, and the debt position is possible to be force settled at any time, users always do not have enough incentive to short and then bitCNY is always in low supply level, this restrict the growing of relevant economy, so what is proposed is to set a compensation from holder to shorter and lower the force settlement volume limit, these will reduce the risk of shorters and encourage them to provide more bitCNY supply. 
# Rationale

The force settlement offset can be seen as a service fee that holder pay to shorter at the time of force settlemetn happens, the offset need to be set a proper value that can balance the risk of holders and shorters, the 0 offset setting is not reasonable enough as in common financial logic the collateral should not be force settled without any compensation if the collateral price does not fall below the margin call price, on the other hand, if the offset is set too high, holders will be discouraged to hold the smartcoin as high offset can make force settlement not feasible. as a reference, in the initial time after creation, TCNY has been set a 2% force settlement offset, the consequence is that almost all the holders do not want to request force settlement, even when BTS price is very low, based on these reference, now 1% offset is proposed.

Suppose there's no shorting happens in 24 hour, then the maximum volume that can be force settled in this period is supply \* (1-(1-q)**24) , here q = maximum_force_settlement_volume.

Here p=(1-(1-q)**24) represent the maximum percentage of the supply that can be force settled in 24 hours, then

if q=3%   p=51.9%
if q=2%   p=38.4%
if q=1%   p=21.4%
if q=0.5% p=11.3%
if q=0.2% p=4.7%

q=0.5% should be a reasonable choice with at most 11.3% of supply can be force settled in one day. 
# Specification

A committee proposal will change the 2 parameters of bitCNY from

force_settlement_offset_percent = 0
maximum_force_settlement_volume = 2% per hour

to

force_settlement_offset_percent = 1%
maximum_force_settlement_volume = 0.5% per hour

The expiration time will be set to 30 days for relevant users to respond and operate.
# Discussion

Will bitCNY be "devalued" after this change?

If we can say force settlement offset is a service fee paid from holder to shorter. this change is just to ask holders to pay 1% fee to shorters while requesting force settlement, and they really should pay some fee. bitCNY is really "devalued" with 1% if force settlement is the only way for this smartcoin to quit, but bitCNY has some other way to quit, including to trade with other assets, to deposit to btc38 and to withdraw through gateway. and the collateral of the smartcoin are always there without any change, so the "devalue" is slight enough if not zero. The holders also have a long expiration time to request 0 offset force settlement to quit. So comparing to the benefits this change will bring to the relevant economy, this "devalue" is not a problem. 

Should this change be applied to other smartcoin such as bitUSD?

Based on the same logic, it is also necessary to apply the same change to other smartcoins, but to be cautious, it is proposed to first apply the change to bitCNY, after obesevation and review with long enough time, it can be considered to apply the change to other smartcoins.
# Copyright

This document is placed in the public domain.

**Comment by xeroc** [comment]
https://github.com/bitshares/bsips/blob/master/bsip-0016.md

**Comment by abitmore** [comment]
Applied, closing.
