### ISSUE TITLE
BSIP57: Managed Vesting Balances

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bsips#136]
Original discussions:
- https://bitsharestalk.org/index.php?topic=27361.0
- https://steemit.com/bitshares/@sschiessl/bsip-draft-managed-vesting-balances-plus-savings-account-discussion-20181105t152833150z-post

All further discussion should be within this issue

**Comment by abitmore** [comment]
Closing the issue since nothing has been discussed here. The draft is in the repository already: https://github.com/bitshares/bsips/blob/master/bsip-0057.md
