### ISSUE TITLE
Optimization to Force Settlement Parameters of bitUSD

### ISSUE THREAD

**Issue by bitcrab** [bitshares/bsips#14]
```
BSIP: 0017
Title: Optimization to Force Settlement Parameters of bitUSD
Authors: Jerry Liu<jerry.liu@transwiser.com>
Status: Draft
Type: Protocol
Created: 2016-08-01
Discussion: https://bitsharestalk.org/index.php/topic,22936.0.html
Worker: no
```
# Abstract

We here propose to optimize the settlement _offset_ and maximum settlement _volume_ of bitUSD to encourage shorters to provide liquidity in the bitUSD:BTS market with a lower risk.
# Motivation

Smartcoins are stable currencies and also leverage tools, smartcoin supply can only grow while more and more users select to use this leverage tool, because using this leverage tool means generating smartcoin by shorting with BTS as collateral, and the debt position is possible to be force settled at any time, market participants do not have enough incentive to use the leverage tool and as a consequence smartcoin supply is always in low level. This restricts the growing of relevant economy. We have changed bitCNY parameters and effectively made bitCNY supply grow up, now we propose to do the same change to bitUSD as have done on bitCNY  -  set a compensation from holder to shorter and lower the force settlement volume limit, these will reduce the risk of shorters and encourage them to provide more bitUSD supply. 
# Rationale

The force settlement offset can be seen as a service fee that holder pay to the settled shorter at the time of force settlement. The offset need to be set a proper value that can balance the risk of holders and shorters. A 0 offset is not reasonable enough as in common financial logic the collateral should not be force settled without any compensation if the collateral price does not fall below the margin call price; on the other hand, if the offset is set too high, force settlement will be unfeasible as "last resort" for value express. another parameter -  the max hourly force settle volume -  should be low enough to prevent sudden settlement to force shorters out quickly. experience in bitCNY shows that 1% offset and 0.5% max hourly force settle volume are comparatively reasonable combination.
# Discussion
### Will bitUSD be "devalued" after this change?

It is our opinion that _force settlement_ is a service. This change is to ask holders to pay a small percentage (1%) fee to shorters when requesting force settlement. currently bitUSD is in low supply and badly pegged, partly because it do not attract enough market participants, If the proposal is accepted by the committee, we can expect more market participants will come and help bitUSD to peg better. after the change bitUSD can be better traded in the regular markets with other assets. it will not be "devalued", "force settlement " is not a common value express way but the "last resort" and should not be used directly to judge the value of the smartcoin. 
### Should this change be applied to other smartcoins?

Based on the same logic, it makes sense to apply the same change to other smartcoins, but to be enough cautious, it is still proposed to apply the change to only bitUSD this time, one choice is to apply the change to all the other fiat-pegged smartcoins next time.  This, however, will require another written proposal and is not covered by this BSIP.
### Does this proposal break a promise?

Yes, but maybe not! There were promises made that bitassets can be settled at any time at the _fair price_ (price feed). With this proposal, we ask for a percentage fee for the settlement service. This can be interpreted as breaking a promise while it could also be interpreted as a change in fee schedule: "Settlements are free for the first few months, after that they are 1%".
# Summary for Shareholders

Currently, there is no settlement offset which means that longs can settle their position _at_ the price feed. The consequence is that market participants are not selling their bitUSD at the price feed but slightly higher knowing that they could always settle at the feed via settlement.

By asking for a percentage of the settled volume, the premium is assumed to be reduced and bitUSD will be traded more tightly around parity. Since the settlement offset is paid by the long position to the settled shot position, shorters are compensated for providing bitUSD. Because settlements happen on a 24h notice, we expect shorts to adjust their collateral to _catch_ settlement orders and make a profit.

For the long position, the settlement offset appears as if it was a percentage fee for the serivce of settlement after 24h.
# Copyright

This document is placed in the public domain.

**Comment by abitmore** [comment]
Applied, closing.
