### ISSUE TITLE
Change ownership of CASH.USD and CASH.BTC Smartcoins to committee-account

### ISSUE THREAD

**Issue by merivercap** [bitshares/bsips#15]
BSIP: 0018
Title: Change issuer of CASH.USD and CASH.BTC Smartcoins to committee-account
Authors: Jun Dam (jun@bitcash.org)
Status: Draft
Type: Protocol
Created: 2016-08-14
Discussion: https://bitsharestalk.org/index.php/topic,23010.0.html
Worker: no

---
# Abstract

We at Bitcash propose to have the Bitshares committee custody and control the the CASH.USD and CASH.BTC Smartcoin assets. 

---
# Motivation

Several months ago we created CASH.USD and CASH.BTC Smartcoins to provide an alternative to bitUSD and bitBTC primarily because we felt that the current Smartcoin designs were not optimal and could significantly deter adoption. We strongly believe that the Smartcoin designs we have implemented are significant improvements over the current bitUSD and bitBTC designs. However after deep consideration, we at Bitcash have decided that decentralized key management is vital to security and that it is important to implement committee custody of Smartcoins sooner than later. 

---
# Rationale

Having alternative Smartcoins with distinct designs in the Bitshares ecosystem is extremely beneficial to the Bitshares ecosystem.  Making changes to a Smartcoin design is already contentious and difficult, especially when the Smartcoins are already being used.  Any design change with bitUSD or bitBTC could upset existing holders.  Some changes in design parameters could improve liquidity whereas others may be detrimental.  It is also difficult to isolate the cause of any particular improvement in liquidity because many external factors beyond design parameters affect liquidity.  Hence having a couple alternative designs at the same time could increase the chances of success and expedite mainstream adoption.  Dan Larimer has mentioned the experimental nature of Smartcoin parameter designs and purposely created Privatized Smartcoins to allow competition and even give companies an opportunity to monetize a good design. However our intent has always been to create an optimal design to benefit the Bitshares ecosystem. The best designs will attract the most participants, businesses and liquidity. Even small changes in parameters can make a significant difference. 

Currently there are proposed changes to bitUSD under BSIP #17.  We support those changes and should make it somewhat closer to our CASH.USD design. However the reduction of forced settlement from 20% to 0.5% per hour is not enough. CASH.USD does not have forced settlement.  Furthermore the Maximum Short Squeeze Ratio for both bitUSD and bitCNY remain at 110% instead of 100.1% for CASH.BTC and CASH.USD. At this early stage of adoption, experimentation with more than one Smartcoin design is important.
## Background

Our Smartcoins are defined to be worth the same as the corresponding asset. Hence one CASH.USD should trade for $1 and one CASH.BTC should trade for one bitcoin. Companies like Bitcash are expected to maintain bridges to support the 1:1 exchange or place orders at the price feed when necessary to reinforce the price feed and provide CASH.USD and CASH.BTC holders the ability to liquidate at the price feed when necessary.  The price feed determines the social consensus of what amount of BTS is equivalent to $1 or 1 bitcoin at any given time.  Currently we use witnesses to provide the price feed.  All the parameters are designed to support the social consensus that the value of CASH.USD is equivalent to one dollar and the value of CASH.BTC is equivalent to one Bitcoin.
## Differences compared to bitUSD and bitBTC:
- Merchants or CASH.USD holders will not have a price floor guarantee.  If merchants/holders do not have a gateway or buyers that will exchange a CASH.USD 1:1 for a dollar, they may have to exchange it for BTS and may get more than or less than one dollar when selling BTS.  
- User forced-settlement will be disabled to protect CASH.USD creators.  Any user can create CASH.USD and will not be burdened with the uncertainty of being manually force-settled and should be comfortable creating and maintaining a long-term supply of CASH.USD.  Creators of CASH.USD will only be force-settled when they are undercollateralized.
- The maximum short squeeze price is set at 100.1% so that when creators who borrow CASH.USD into existence are margin-called, the settlement price will be at the price-feed.
## Parameters:

MSSR: 100.1%
MCR: 175% 
No forced settlement
Witnesses provide price-feed  
## Theory:

All fiat dollars are treated the same even when they are distinctly different.  Just think about the the qualitative difference between coinage, checkbook money, federal reserve notes, and digital dollars from Venmo/Square Cash/Paypal.  The reason such varied forms of money are treated as equivalent is because there is a social consensus of dollar equivalence.  Without a social consensus, digital dollars may be traded for more than a dollar for its convenience, and coinage less than checkbook money for its inconvenience.  However most everyone treats any form of the dollar the same.  

Banks create checkbook money, the dominant part of M1 money supply, out of thin air and allow this money to circulate in the economy.  Usually banks use real estate assets as collateral to create monetary assets.  These monetary assets aka debt-money aka checkbook money  are merely accounting entries, but they are treated the same as federal reserve notes (green paper dollars in your wallet) or coins.  Again there are distinct qualitative differences between checkbook money, federal reserve notes & coins.  The current Bitshares system functions precisely the same way as banks, but instead of real estate, BTS is used as collateral.

Banks create debt/checkbook money that are defined to be dollars, and the real estate collateral that backs this money can fluctuate in value.  As long as the real estate value is greater than the value of the money banks create, banks are not concerned.  In the Bitshares ecosystem, members can create an equivalent type of debt/checkbook money on the blockchain when they create CASH.USD (or borrow CASH.USD) into existence using BTS.  Hence there should be no difference between the checkbook money banks create in the current banking system compared to the CASH.USD that members create on the Bitshares system as long as the social consensus defines both types of debt-money to be valued as dollars.  

What if someone trades CASH.USD for something other than a dollar?  In a free market someone can trade three quarters for one federal reserve note or a one dollar check, but that doesn’t mean trading three quarters for a dollar is part of the social consensus nor should a number of bad trades dictate what the social consensus is.  Hence as long as there is no external reason or design parameter that would lead one to believe CASH.USD is worth anything other than a dollar there will be a social consensus that it is.  The current CASH.USD design should support this reasoning.

---
# Specification:

**Account owner of bitcash-reg will change the issuer designation of CASH.USD and CASH.BTC Smartcoins from bitcash-reg to the committee-account.**

We do recognize that in doing so the committee will have control over future parameter changes. However we would like the committee to **acknowledge and uphold the principles of our alternative design**, namely:  1) the forced settlement feature is to remain permanently disabled (bitcash-reg may permanently disable before transfer ) 2) the maximum short squeeze ratio is to be as close to 100% as possible so under-collateralized settlement will be sold as close to the price feed as possible. These parameters are foundational to the success of CASH.USD and CASH.BTC and key to their designs. 

---
# Discussion:

_Will having two Smartcoin assets be confusing for users?_
Bitcash will independently promote CASH.USD and CASH.BTC.  Any other company or user can choose to do the same.  It will just be one of the many tradeable assets among the many Smartcoins and UIAs.  Although having too many Smartcoin options may be confusing, having just 2 or even 3 variations is worth any minor inconvenience.

_What maintenance or changes should the committee expect in the future?_
There should be very little maintenance other than keeping the fee pool balance funded.  The parameters for the Smartcoins are based on the principles stated above and should require little to no changes going forward.  

---
# Summary:

We propose to have the Bitshares committee custody and control the the existing CASH.USD and CASH.BTC Smartcoin assets. Our main motivation is to decentralize ownership of these alternative Smartcoins.  The transfer of ownership should require no action from the Bitshares committee and will only require the committee to keep the fee pool funded after the change in ownership of the asset.  One CASH.USD is defined to be equivalent to a US dollar and expected to be traded 1:1 excluding fees by social consensus.  One CASH.BTC is defined to be equivalent to one Bitcoin and expected to be traded 1:1 excluding fees by social consensus. 

---
# Copyright

This document is placed in the public domain.

**Comment by pmconrad** [comment]
Seems to be dead. Closing.
