### ISSUE TITLE
New BSIP: Add Merchants & Tellers map to Spotlight

### ISSUE THREAD

**Issue by Agorise** [bitshares/bsips#152]
BSIP: <BSIP number>
    Title: <BSIP title>
    Authors: Agorise, Ltd.
    Status: Draft
    Type: Informational
    Created: 2019-03-01
    Discussion: <url>

# Abstract
Getting mass adoption of the Bitshares blockchain is actually quite easy now that the tools for it have been built. What Bitshares needs now (in addition to more tools of course) is marketing. 
 
PalmPay is not just a Point Of Sale system built on the Bitshares platform, but it is also a growing network of Ambassadors of the platform (https://palmpay.io/ambs). 
 
More and more merchants are adopting Bitshares: 
https://palmpay.io/merchants 
 
Tellers are people who exchange fiat currencies with cryptocurrencies, and vice versa. Tellers also assist merchants with fiat settlement. This eliminates the need for centralized exchanges/gateways and bridges. 
 
We would like to add a "Merchants & Tellers card to the Spotlight page in the bitshares-ui reference wallet. When clicked on, it loads up a searchable table and map, similar to what you see here: 
https://palmpay.io/merchants 
 
# Motivation
Support Bitshares-supporting merchants: Encourage Bitshares users to visit merchants that accept Bitshares' assets. 
 
Encourage Tellers; local trades of Bitshares assets with fiat (the BiTSy app can be used for this as well). 
# Rationale
# Specifications
The code for the searchable map of Merchants & Tellers comes from a server maintained by Agorise, Ltd. That server provides a public web service and that same database of Merchants & Tellers can be found on the map in the BiTSy android wallet. 
 
The code to display the map and advanced search is located here: 
https://github.com/Agorise/palmpay.io-website/tree/master/src/components/pages 
# Discussion
# Summary for Shareholders
There is no expense to Bitshares shareholders since the servers which run the web service are maintained by Agorise, Ltd. These servers host the database which keeps track of all Ambassadors, Merchants and Tellers which the bitshares-ui clients can leverage.
# Copyright
Public domain.
# See Also

**Comment by pmconrad** [comment]
I think is is not really relevant to the BSIP process. Perhaps better open an issue in the ui repo. https://github.com/bitshares/bitshares-ui

**Comment by xeroc** [comment]
I agree with Peter. This is a request for UI epository.

**Comment by pmconrad** [comment]
Closing as per comments.
