### ISSUE TITLE
BSIP58's type should not be protocol, and its status is confusing

### ISSUE THREAD

**Issue by abitmore** [bitshares/bsips#166]
IMHO it's not a protocol change, because no code need to be changed.

By the way, for this kind of BSIPs that needs continuous voting, I think it's better to have a different status other than "draft", for example, perhaps "accepted" or "voting" is better?

**Comment by pmconrad** [comment]
Type should be `Informational`.

Status discussion also applies to BSIP-60, see https://github.com/bitshares/bsips/issues/131#issuecomment-486290708

**Comment by ryanRfox** [comment]
Updated README for BSIP58 and BSIP60 to "Accepted" status.

**Comment by abitmore** [comment]
Closed by #173.
