### ISSUE TITLE
Onchain margin position management

### ISSUE THREAD

**Issue by froooze** [bitshares/bsips#167]
# Problem
1. Settlement is now only available from bitAsset -> BTS, but not from BTS -> bitAsset
2. Target collateral ratio only works, when a margin call happens, but not before
3. Increasing CR, needs a collateral removal first (decreasing CR) 

# Onchain margin tools
To cover the other side of margin trading and offer a BTS call outside of a margin call:
- Increase CR (=target collateral ratio)
- Close the margin position by selling as much BTS to cover the difference of BALANCE and DEBT
- Close margin and sell afterwards X% of the BTS from the margin position to the borrowed bitAsset

## Additional parameters:
- Start date
- MSSR

**Comment by abitmore** [comment]
Context: earlier discussion in https://github.com/bitshares/bitshares-ui/issues/2660

**Comment by sschiessl-bcp** [comment]
> # Problem
> 1. Settlement is now only available from bitAsset -> BTS, but not from BTS -> bitAsset
> 2. Target collateral ratio only works, when a margin call happens, but not before
> 3. Increasing CR, needs a collateral removal first (decreasing CR)
> 
> # Onchain margin tools
> To cover the other side of margin trading and offer a BTS call outside of a margin call:
> 
> * Increase CR (=target collateral ratio)
> * Close the margin position by selling as much BTS to cover the difference of BALANCE and DEBT
> * Close margin and sell afterwards X% of the BTS from the margin position to the borrowed bitAsset
> 
> ## Additional parameters:
> * Start date
> * MSSR

Can you please elaborate a bit more on 1.-3. and what your desired functionality is?

**Comment by abitmore** [comment]
As mentioned it's related to #156. Likely also related to #161. I'd like to have a big BSIP adding all the new parameters for bitAssets so asset creator can decide to apply what rule set.
