### ISSUE TITLE
New BSIP: Add option to update an asset's precision

### ISSUE THREAD

**Issue by abitmore** [bitshares/bsips#187]
Currently precision of asset can't be updated, it's annoying when a user accidentally set an incorrect precision when creating the asset.

This BSIP propose a protocol change so that precision can be updated when there is zero supply.

To implement, can add a field in `extensions` of `asset_update_operation`.

**Comment by xiao93** [comment]
support, thank abit.

**Comment by abitmore** [comment]
This will be addressed in BSIP48 (https://github.com/bitshares/bsips/pull/216). Closing.
