### ISSUE TITLE
bsip#10: Percentage-based transfer fee solution based on CER

### ISSUE THREAD

**Issue by neura-sx** [bitshares/bsips#3]
```
BSIP: 0010
Title: Percentage-based transfer fee solution based on CER
Authors: Jakub Zarembinski <jakub.zarembinski@neura.sx>
Status: Draft
Type: Protocol
Created: 2015-12-27
Discussion: https://bitsharestalk.org/index.php/topic,20789.0.html
Worker: t.b.d.
```
# Abstract

This is a proposal aiming to introduce a percentage-based transfer fee solution as an alternative to the current flat rate. The main goal is to make BitShares competitive for transfers below the equivalent of $5 while keeping the referral program unharmed (or even strengthened).

The idea is to derive the BTS value of an asset transfer from the Core Exchange Rate (CER) defined by the asset's issuer.  A complementary change in the referral system is also needed in order to prevent abuse on the part of referrers.

The only stakeholders affected by this proposal are referral businesses as their revenue stream will be negatively affected for smaller transfers but instead positively affected for larger ones. As for shareholders in general, the change is positive because BitShares will become more competitive in terms of pricing when compared to the legacy systems. 

The financial effect for the blockchain itself will be neutral as all profits (or losses) will be absorbed by the referrers. However, an overall increase in the network's revenue is expected as it is safe to assume that when small transfers are cheaper, there will be more of them and each of them will contribute to the network's revenue. As we have it know, most blocks are empty, which from a business perspective is a clear waste of company's resources.
# Motivation

Having a flat transfer fee of 30 BTS for non-LTM users, currently BitShares cannot be regarded as a competitive payment solution for transfers between the equivalent of $1 and $5. The current fee in this range is above 2%, which is way more than any legacy system wants to charge its customers.

There are two important objectives this proposal aims to achieve:
- to allow users to pay lower transfer fees for smaller transfers (while charging them more on bigger transfers)
- to allow referrers to earn extra income associated with bigger transfers (while taking away from them the current income associated with smaller transfers).
# Rational

The simplest way to solve the "high transfer fee" problem would be to lower transfer fees for all assets. However this would effectively kill the referral program. On the other hand, a simple percentage-based transfer fee system is not doable as for most assets we do not have a viable way to determine their exact value at any given time. This is mainly due to the fact that most markets are very illiquid but also due to the difficulty of establishing an asset's price in a manner which is deterministic enough to reliably prevent unintended hard-forks.

Also, a percentage-based transfer fee system, if introduced without any modifications to the referral program, would open up the possibility for referrers to game the system by transferring small amounts back and forth between their own accounts just to collect the referral award at the expense of issuers. Therefore, for assets enjoying a percentage-based transfer fee system, referrers' revenue structure has to be percentage-based as well.
# Specifications
#### The assumptions

The following description uses a fictional asset called BAX but this solution can be applied to all assets (i.e. SmartCoins, private bit-assets, UIAs and FBAs) and all non-stealth transfers. Also, what is described below refers to pay-as-you-go users. For LTM users exactly the same rules apply, except for the fact that in this case the referrer's income is redirected to the user's cash-back fund.

Values used in the description are just an initial proposal, the actual values will be determined be the committee.
#### The concept

The transfer fee can be paid either in BTS or BAX.
1. If the user chooses to pay the fee in BTS:
   - The transfer fee is equal to 1% of the BTS value of the BAX amount being transferred, adjusted by a floor (i.e. minimum fee) and a cap (i.e. maximum fee): 6 BTS and 300 BTS respectively. So effectively the transfer fee is 1% but it is never less than 6 BTS and never more than 300 BTS.
   - To establish the BTS value of the transfer, CER is used.
   - The fee paid by the user is split as follows: 6 BTS goes to the network, any excess above 6 BTS goes to the referrer.
   - The issuer does not earn anything.
2. If the user chooses to pay the fee in BAX:
   Let F be the transfer fee (expressed in BTS) which was calculated as described in (1).
   - To establish the BAX equivalent of F, CER is used.
   - The issuer receives the entire fee paid by the user in BAX.
   - The following amounts are deducted from the asset fee pool: 6 BTS goes to the network, and (F - 6) BTS goes to the referrer.
   - The issuer makes a profit or loss, depending on CER being above or below the actual BTS/BAX exchange rate.
#### The main issue

What happens when the issuer attempts to artificially lower transfer fees on his asset by pretending his asset is not worth much and deliberately keeping CER below the actual BTS/BAX exchange rate?
- for the user: it's cheaper for him to pay the fee in BTS rather than in BAX
- for the issuer: he makes a profit on all those transfers for which the user, for whatever reasons, decides to pay the more expensive fee in BAX (instead of the cheaper one in BTS)
- for the referrer: no matter if the user pays the fee in BAX or BTS, he is deprived of a large part of the referral reward, as due to distorted CER, transfers are interpreted by the system as involving smaller value than they actually are.
#### How is the issue solved?

By keeping CER artificially low the issuer will effectively discourage users from using his own asset because transfer fees will only be low when paid in BTS, so the process of transferring the asset will be dependent on users having BTS in their wallets to cover the fees. Furthermore, if the issuer distorts CER too much, he'll not be able to benefit from it himself as users will start avoiding paying the fees in BAX. Also, it will be bad PR for the issuer to value his own asset below the market rate. At least in case of SmartCoins and major private bit-assets issuers are not likely to be wiling to sabotage their own assets in this way.

However, if it turns out that a large number of issuers try to game the system, we can introduce the following mechanism aimed at preventing abuse on the part of issuers:
- To enable percentage-based transfer fees, the issuer will be obliged to keep an open ask order on the BTS:BAX market and thus allow anybody to buy BAX at e.g. 120% of CER. As a result, if CER is out of sync with the market rate by more than 20%, the issuer will incur a significant loss.
- If the issuer is not willing to comply with the above requirement, the default flat transfer fee structure will be applied.
#### This is an opt-in feature

As the issuer is the only entity that actually controls CER, the percentage-based transfer fee is meant to be an opt-in feature decided by the issuer. It is safe to assume that most issuers will find it beneficial for their assets because:
- assets which are worth something will benefit from having a reasonable pricing structure for transfers
- assets which are worth nothing or almost nothing (i.e. most UIAs) will be able to be transferred almost for free (for 6 BTS instead of the current 30 BTS).
  However, if an issuer for some reasons does not find the above features beneficial, he will be able to keep the existing flat fee structure.
# Discussion

Being voluntary for issuers, the above proposal is actually targeted to the referral businesses: do they perceive it as a beneficial change for the ecosystem and a fair deal for them? They will need to forgo the referral income on transfers below the equivalent of $2 but will substantially increase their income on transfers above the equivalent of $10. In the range between $2 and $10 they will get on average half of the income they have now. Nevertheless, the main benefit will be indirect: it's much easier to sell a reasonably priced product.

As for the BitShares network itself, the overall impact of this proposal will be positive, as the network's resources will be better utilized. With the current flat fees, most of the blocks are empty. Percentage-based fees will not fix this waste immediately, but will be a step in a good direction and a good foundation for businesses based on small tips and micro-payments above $1.
# Copyright

This document is placed in the public domain.

**Comment by xeroc** [comment]
I would assign 0009 to this. Could you fill in the missing header:

    BSIP: 0009
    Title: <BSIP title>
    Authors: <list of authors' real names and optionally, email addrs>
    Status: Draft
    Type: [ Informational | Protocol ]
    Created: <date created on, in ISO 8601 (yyyy-mm-dd) format>
    Discussion: <url>
    Worker: t.b.d.


From recent discussions I am thinking a (non-technical) Summary for shareholders
makes sense as well (for all bsips - working on it). Does you proposal affect
shareholders? If so, how? See that paragraph as a means to convince shareholders
to vote for you proposal in the case of a hard fork.

**Comment by neura-sx** [comment]
@xeroc I've added the header and also expanded the abstract section a bit to highlight the way this proposal can affect shareholders. It could be expanded further but I'll suggest to stop here and first get some feedback from CNX (especially BM) if this proposal is doable from the technical perspective and viable in terms of protection against abuse.

**Comment by bitcrab** [comment]
you mean one need to pay 100 BTS for transfer 10000 BTS? are you kidding?

**Comment by xeroc** [comment]
Question that needs to be answered (probably by each issuer individually):

* Do I want micropayments?
* Do I want to profit from high-volume transfers?

Also, technically, the costs for the blockchain are fixed independent of the amount that is transferred!

That said, and knowing that I am a huge fan of the KISS principle, I must say that I like @bitcrab proposal more.

**Comment by neura-sx** [comment]
The choice between [1%, 6 BTS, 300 BTS] and [0.3%, 3 BTS, 30 BTS] is not subject of this proposal, this will be decided by the committee. This proposal only aims to offer a new mechanism of charging transfers fees and distributing them to referrers. 
Please do not turn this into a political debate.

**Comment by clayop** [comment]
The fee distribution scheme can be debatable. IMO, the network should come first. So the minimum fee always goes to network, and if 20% of a fee exceeds the lower limit, 20% goes to the network and 80% goes to the referral system.

**Comment by abitmore** [comment]
Please consider adding a "No." column to "Known issues" section, so individual items can be easier tracked.

**Comment by abitmore** [comment]
Already in the repo. Closing here.
