### ISSUE TITLE
Inappropriate silent/uncommunicated rejection of BSIPs 19 & 20

### ISSUE THREAD

**Issue by grctest** [bitshares/bsips#43]
@xeroc I find it inappropriate to have outright rejected BSIPs 19 & 20 without a peer review, private message nor public communication. I presented both of these proposals on the Bitshares hangout, the least you could do when dictating what is an acceptable BSIP is to vocalize your intent to reject it on the hangouts.

Your "Complicance" worker proposal isn't active yet, thus your justification for rejecting these BSIPs lacks consensus. BSIP 20 can be implemented without a BSIP & if that's enough to throw a wrench in BTS' compliance works then what's even the point of your compliance worker proposal since it's doomed to fail?

**Comment by abitmore** [comment]
Is it time to start a poll like [this](https://bitsharestalk.org/index.php/topic,25357.0.html)?

**Comment by abitmore** [comment]
Just noticed that the status has been changed to "deferred".

**Comment by grctest** [comment]
@xeroc Please revert 'deferred' to Draft, for no discourse within the BTS network/community has justified this current status.

**Comment by zhangweis** [comment]
I really hope to see BIP19 implemented. At least an easy way to get distribution(holdings) of any UIA at any moment or at least at the calling time. This way I can make the payouts myself. Currently it's really hard for me to get the distribution of UIA.
BTW, Does BIP19 includes scenario of any amount of dividends of UIA/MPA on UIA holdings? 
Say I have some profit which is in CNY and I want to distribute it to holders of my UIA(say UIA1).

**Comment by abitmore** [comment]
@zhangweis perhaps you can check `asset_api` and / or `snapshot_plugin`.

**Comment by zhangweis** [comment]
@abitmore Actually I've made some changes to snapshot plugin for my own use to support snapshot periodically and only store some asset information to keep the snapshot small. But as this is a quite common requirement for asset issuers, I'd really like to see it implemented at protocol level.

**Comment by zhangweis** [comment]
@abitmore asset_api looks good for most cases. But I need to take snapshots back to 3 days ago for example in some edge cases so I choose to change snapshot plugin. I may use asset_api directly if I had known it and ignore the edge cases.

**Comment by pmconrad** [comment]
@xeroc is there some official statement on this?

**Comment by abitmore** [comment]
Inactive.
