### ISSUE TITLE
Order lost - "Failed to broadcast transaction" error loses order setup

### ISSUE THREAD

**Issue by ai3d-brodie** [bitshares/bsips#47]
When the nodes are not responding well, and i make an order that "Failed to broadcast transaction", then the whole order i set up gets lost, the values disappear from the order buy/sell panel.    I had to recreate the order 6 times before it finally went through.  This is a recipe for a fat finger error x6.
Could you make it so the amounts stay in the GUI panel or alternately have the ability to save an order without placing it so that it can be tried a number of times without creating from scratch again.
Thanks & Cheers

**Comment by pmconrad** [comment]
Thanks for your feedback, however this should be addressed to the bitshares-ui repo: https://github.com/bitshares/bitshares-ui/issues
