### ISSUE TITLE
Port ACCT from Scorum

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bsips#49]
Apparently Scorum have implemented Atomic Cross-Chain Trading in their graphene chain (apparently a steem fork). We should evaluate and port this to BitShares.
https://github.com/Scorum/Scorum/wiki/How+to+do+atomicswap
https://bitsharestalk.org/index.php/topic,25789.0.html

**Comment by AlexShkor** [comment]
Hello from Scorum team! 

Let me share with you the Pull Request with ACCT implementation, feel free to review and comment. We are happy to assist you with an integration of our implementation of Atomic Swap into Bitshares.
https://github.com/scorum/scorum/pull/41

Cheers,
Alex

**Comment by oxarbitrage** [comment]
do we have resources working on this feature already ?

**Comment by pmconrad** [comment]
Closing this since BSIP-44 has been implemented.
