### ISSUE TITLE
BitShares Network Is Overloaded and Needs More Infrastructure

### ISSUE THREAD

**Issue by landry314** [bitshares/bsips#50]
Recently I have been only seeing one or two nodes at a time with medium or high latency and many times my transactions are timing out due to poor server connections...

I am in New York City now and have been in Germany, France, and England recently and have had the same issue so it isn't the network where I am. Throwing out my library files for the BitShares application on Mac OS 10.12 seems to give me a few more or faster connections for a short time then it goes back to slow again. It is very frustrating.

I am wondering if this problem has been happening for many people and if it is just an overloaded infrastructure due to higher use recently. If so, we need a proposal to incentivize more nodes for the blockchain. Pay more to the witnesses or something. This is a serious bottleneck we have hit.

Any suggestions are appreciated!

**Comment by abitmore** [comment]
IMHO this topic doesn't belong to here.

**Comment by landry314** [comment]
Then where does it belong, @abitmore?

**Comment by pmconrad** [comment]
Providing API servers is not part of the witness job.

We already have an active worker for providing infrastructure. Please move the discussion to that thread. https://bitsharestalk.org/index.php/topic,25291.0.html
