### ISSUE TITLE
extend user issued names

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bsips#52]
this is an issue to test the waters on how much interest the bitshares community will have on extending asset names to allow numbers at the end of them. for example issue an asset with the name SP500.

inspired by this issue. https://github.com/bitshares/bitshares-core/issues/620

**Comment by tbone-bts** [comment]
I think this would be a nice change and I assume it would be relatively trivial to implement.  However, I do wonder if perhaps there was a good reason for not allowing numbers in asset names to begin with.

**Comment by oxarbitrage** [comment]
hey @tbone-bts . the code does not allow numbers at the beginning or end of the asset. inside the name it is ok to use them. the issue is to add a  number at the end to have indexes names available. not sure why this is not allowed.

**Comment by abitmore** [comment]
BSIP 0037 created with #62 : https://github.com/bitshares/bsips/blob/master/bsip-0037.md .
