### ISSUE TITLE
The problem of Witnesses and committee votes.

### ISSUE THREAD

**Issue by bxgzi** [bitshares/bsips#53]
When a person votes for multiple witnesses and the committee, the number of votes each witness and committee receives should be his market value/the number of votes cast by him.

Otherwise one can register several witnesses and committee account, some people vote for his multiple accounts when he won the voters' accounts are so value vote, he could only become a witness and committee results but became more.

**Comment by pmconrad** [comment]
Seems to be dead - closing.

(I also think the suggestion is not good because it means that people who are voting for fewer candidates have more power than those voting for many. We *want* people to vote for many though, for better decentralization.)
