### ISSUE TITLE
Future settlement of orders across future blocks

### ISSUE THREAD

**Issue by sunburntcat** [bitshares/bsips#67]
A futures market where assets are bought/sold and then released on the settlement date can provide a good amount of liquidity to the market. This is especially true for Smartcoins, where speculation is essential to keep the price pegged to the underlying asset.

A true free-market (where there no is learning curve to use the Futures vs. the current implementation) completely eliminates the need to lock up more collateral than a 1:1 ratio. This is because the Futures market acts to "stabilize" the current market, because future volatility is inherently built into the market itself.

This stability leads to a reduction (elimination?) of "Black Swan" events with the following situation:

In BitShares, if there is not enough current liquidity on either the buyer/seller side, a “black swan” event occurs, where collateral is destroyed in the opposite direction to allow the price trend to reverse. This can happen if the underlying asset (BTS for example) is falling so quickly, that no one even wants to lock up their BTS into a smart contract and would rather sell it. 

With the allowance for asset settlements that take place in the future, someone can see that the price of the backing asset may be currently falling rapidly (where there is a risk of a black-swan event), but can openly see that the market expects a strong rebound in 30 blocks. Therefore, they are comfortable locking up some BTS now in anticipation of future upward price movement. This leads to market-stability as this "Buy" order puts upward pressure on the price.

**Comment by pmconrad** [comment]
Seems to be dead - closing.
