### ISSUE TITLE
Discussion: about voting on account creation

### ISSUE THREAD

**Issue by abitmore** [bitshares/bsips#68]
In DPoS-based systems including BitShares, voting is important, voter turnout is important.

In BitShares, an existing account can explicitly delegate its voting right to another account, by setting the latter account as "proxy" via `account_update_operation`.

All accounts except the ones in genesis block need to be registered by *registrars*. After registered, usually the owner of the new account will have full control. There are several public registrars, known as *faucets*, which pay the account registration fee for the new accounts.

Technically, registrars have the ability to set voting options when creating a new account, e.g. voting for some items, set the new account's proxy to a specified account, etc. This is actually a double edged sword.

Pros:
* A voter doesn't have to cast the vote by herself with a new operation if the registrar can honestly set the voting options for her as she requested. The voter doesn't need to pay additional fees. It saves a bit storage space for the blockchain.
* Overall voter turnout will be increased if more voters start voting on registration.

Cons:
* Registrars can abuse the power by voting in their own interests for ignorant users or users who don't care about voting. This can be significant due to voter apathy. Users who actually care can change the settings after got full control over their accounts.

IMHO registrars should be neutral, and it's best if it can be done with proper governance rules.

Technically, voting settings specified in `account_creation_operation` can be ignored with a hard fork. We can also remove the default voting settings with a hard fork for accounts that didn't ever change voting settings after created.

However, a registrar can get around the limitation by creating new accounts with keys it control, then vote, then change keys to the keys specified by the requesters. Although this need some efforts, it's not too hard.

Other options include:
* Invalidate voting options when BTS balance of an account become below a threshold.
* Require a non-voting period after an account is created.
* Invalidate voting options if an account didn't vote (or active) in a period, as suggested in [BSIP 5](https://github.com/bitshares/bsips/blob/master/bsip-0005.md) and some posts elsewhere.

All these new limitations are controversial since we need to define the thresholds.

**Comment by pmconrad** [comment]
Closing because the community seems to have accepted self-proxying by registrars. Feel free to reopen if you see a need for this.
