### ISSUE TITLE
About BSIP 39: make the approval optional

### ISSUE THREAD

**Issue by abitmore** [bitshares/bsips#71]
Since sometimes the proposer don't want to approve immediately, it's better if she has an option to decide whether approve.

**Comment by abitmore** [comment]
> You recommend to extend "proposal_create" with another extension to add a "flag" for this? Something like, "add_proposers_approval"?

Yes. IMHO it's not a security related change, changing default behavior is not the best option. It's better to maintain backward compatibility, avoid breaking existing applications.

**Comment by abitmore** [comment]
> How about an extension to the `proposal_create_operation` that let's you define whether to auto-approve or not?

That's the idea..

**Comment by syalon** [comment]
Is this BSIP currently suspended? I see that the initial version of the [PR](https://github.com/bitshares/bitshares-core/pull/1368) has been submitted and is also considered backward compatible. We should probably complete the final draft of BSIP and conduct voting. What do you think? @xeroc

**Comment by ryanRfox** [comment]
No @syalon this BSIP is still in draft state. 

@xeroc I feel this BSIP should be cleaned up slightly before we put it up for a vote:

- [ ] Discussion 
  - [ ] Add this Issue's URL along with https://github.com/bitshares/bitshares-core/issues/138
  - [ ] Add summary of of both threads at the bottom of the document
- [ ]  Abstract, Motivation and Rational - refactor these to include the discussed topics and outcome. They seem lacking depth.
- [ ] Specification - more detailed design
- [ ] Summary for Shareholders - include scope of proposals

In my opinion it was merged prior to "done" but that's just an opportunity to revise it now. The concept is good and should be put to vote.

**Comment by abitmore** [comment]
Please review PR #235.

**Comment by ryanRfox** [comment]
Thank you @abitmore for addressing the items in the list above. I ticked them off as complete. Let's proceed within the PR for review, merge and ultimately voting.

**Comment by abitmore** [comment]
Done.
