### ISSUE TITLE
New BSIP discussion: Require UIA owner permission to use UIA as backing collateral for an MPA?

### ISSUE THREAD

**Issue by grctest** [bitshares/bsips#80]
#### Should we require UIA owner permission to use UIA as backing collateral for an MPA?

Recently, [issue #1537](https://github.com/bitshares/bitshares-ui/issues/1537) in the bitshares-ui Github repo highlighted the fact that despite the UI and documentation indicating that UIA cannot be used to back an MPA on the BTS DEX, the reality actually is that UIA are an allowed backing collateral asset type in the core code.

This BSIP is not arguing for/against UIA being used as an MPA's backing collateral, because this is already enforced by core (Abit has a testnet asset configured as such).

The purpose of this BSIP discussion is to whether or not you should require owner permissions/approval of the asset being assigned as backing collateral for a new MPA.

##### Why I think we should require permission

* Any assets locked away as MPA backing collateral cannot be reclaimed/recalled by the UIA owner (even by force). This has the consequence of being unable to reduce the supply to 0, potentially preventing asset settings from being changed or the asset from being fully shutdown.
* By 'wrapping' an UIA in an MPA 'container' the MPA owner can effectively impose new asset settings over the existing UIA flags/permissions/settings to the potential detriment of the UIA owner.

##### Why perhaps we shouldn't require such permissions

* An asset owner may refuse (or be unable to) provide permission to use the asset as backing collateral, requiring an alternative asset for backing collateral.
* The committee may be overwhelmed with requests to use committee owned assets as backing collateral, though that's subjective.
* The committee would have a greater centralized control of backing collateral selection on the BTS DEX, however that could result in more private MPAs being created. The committee size could be increased too to offset risk.
* Existing MPA with non-BTS backing collateral may make implementing such a permission requirement too complex? Perhaps existing MPA could be exempt?
* What if the asset owner removed their approval at a later date? It'd have to be permanent approval unless supply was 0.
* What happens if you have owner permissions of the backing asset & MPA, then transferred the backing asset ownership to another account?
* Being able to avoid market fees and replace restrictive permission flags with an MPA is pretty cool.

##### Exclusions:

* The Bitshares core token should be excluded, as nobody has ownership permissions over it.

----

So, what are your thoughts?

Note: [This is a mirrored github post!](https://github.com/bitshares/bsips/issues/80)

**Comment by jiefangqian** [comment]
Support ,I think the permission is a user contract ,so we should name MPA for  MPCA(Market pegged contract assets).

**Comment by happyconcepts** [comment]
As designed, there is a distinct difference on Bitshares between MPA and UIA, and I think it is for good reason. But from this thread I would be interested to know how others view the difference...

So why is this change needed, really?

I have already read the above and I feel like y'all are getting creative in a dangerous area so I want to understand. Thanks in advance.

**Comment by grctest** [comment]
> As designed, there is a distinct difference on Bitshares between MPA and UIA, and I think it is for good reason. But from this thread I would be interested to know how others view the difference...

They serve different asset purposes - MPAs have decentralized issuance and backing collateral maintained by the blockchain where as UIA have centralized issuance and no proven backing collateral (gateways have backing but not provable on the blockchain).

> So why is this change needed, really?

The proposed change is to require owner permission|approval to use another asset as backing collateral for an MPA, because an MPA imposes a new set of flags & permissions over the existing backing asset settings & the asset owner cannot force reclaim assets out of MPA backing collateral.

By imposing new MPA asset settings (flags/permissions) over the backing collateral, you could evade imposed holder|market whitelists, you could re-enable disabled features like confidential (stealth) transactions, evade market fees & prevent reducing asset supply to 0 (preventing some asset setting changes).

It's already possible to create an MPA using MPA|BTS via the UI & attempting to select an UIA as backing collateral caused an UI error message, but it's always been possible via the CLI - soon it'll be possible to create an MPA using UIA via the UI: https://github.com/bitshares/bitshares-ui/issues/1537

**Comment by happyconcepts** [comment]
> It's already possible to create an MPA using MPA|BTS via the UI & attempting to select an UIA as backing collateral caused an UI error message, ** but it's always been possible via the CLI **

So my healthy skepticism doesn't believe you until I see an example ( the more the better ) of existing MPA's that are backed by UIA instead of BTS.

**Comment by happyconcepts** [comment]
But the larger issue for me here is twofold: 

1. If you don't require MPA to be backed by any collateral, then why even have MPA in the first place? And I like the idea of MPA, it's why I came to BitShares. 

2. In other words, I sense you are talking about making the system smarter, and I agree with this mission. But I would propose adding this functionality via bitshares' evolution toward "smart contracts" in some other way than removing whatever credibility MPA's have thus far managed to garner in the marketplace.

**Comment by abitmore** [comment]
@happyconcepts please check discussions in https://github.com/bitshares/bitshares-ui/issues/1537 as well as `Privatized SmartCoins` mentioned in this document: https://bitshares.org/technology/user-issued-assets/#privatized-smartcoins-stable-cryptocurrencies

**Comment by grctest** [comment]
> @happyconcepts wrote:
>> @grctest wrote:
>> It's already possible to create an MPA using MPA|BTS via the UI & attempting to select an UIA as backing collateral caused an UI error message, ** but it's always been possible via the CLI **
> So my healthy skepticism doesn't believe you until I see an example ( the more the better ) of existing MPA's that are backed by UIA instead of BTS.

I believe that @abitmore has such an asset in the Bitshares testnet : https://testnet.bitshares.eu/market/ASDFUSDA_ASDFB

> 1. If you don't require MPA to be backed by any collateral, then why even have MPA in the first place? And I like the idea of MPA, it's why I came to BitShares.

There are different uses for the MPA asset on the BTS DEX:
* Official bitasset/smartcoin MPA (MPA owned by the BTS DEX committee account)
* Private MPA - backable by **any** asset on the BTS DEX
  Exceptions:
  * Prediction markets - Not sure if by core/GUI enforcement, they have limited lifetime.
  * User Issued Assets (UIA) - by UI rule enforcement only. I'm unsure if the core changed to allow this in the testnet, but there are no explicit rules against UIA as backing collateral - only the UI rule in the client.

Nobody is proposing changing bitassets/smartcoin backing collateral, they will all still use BTS. The matter of UIA being used as backing collateral I do agree seems alien to me - I thought that MPA were only backable by BTS and other MPA, not UIA. 

What's on topic though is whether or not you should require permission to use an asset as backing collateral (or require inheriting the settings of backing collateral) as there are potential consequences for the collateral asset owner.

**Comment by happyconcepts** [comment]
> but there are no explicit rules against UIA as backing collateral

The comments clearly indicate why it isn't allowed.

**Comment by grctest** [comment]
What comments? If you want Uia to never be backing collateral then make
your own bsip on that topic.

**Comment by happyconcepts** [comment]
The comment by @dan in the codebase  where the UI prevents this. I posted it in that bsip.

And you really shouldn't assume that I don't want UIA used as collateral. Come on, did you even read my earlier responses?

Has BSIP become a charade where bitshares whales just make changes without discussion? That seems to happen too frequently on the UI side. Here I am trying to discuss an issue in bitshares-core and it doesn't feel any different so far.

**Comment by grctest** [comment]
You didn't post any comment by Dan in either of these issues.

The topic of Uia as backing collateral is entirely off topic in this
thread, make your own thread to discuss Uia as backing.

This thread is a bsip discussion, so your last point is invalid.

**Comment by happyconcepts** [comment]
Yes I did spend the time to review the code and post the relevant comments within that codebase...and was indeed surprised to see that you were there in that issue thread so either your memory is poor or you are spreading FUD?

Let's work together, even if we disagree huh?

Issue #1537 in the bitshares-ui repo is titled:

## Can't create a smartcoin which is backed by an UIA #1537

And the relevant code comment in the graphene is thus (please don't make me spoon feed this to you a third time):

# "May not create a bitasset backed by a bitasset backed by a bitasset."

**Comment by happyconcepts** [comment]
So bottom line if you're going to change it .... I don't think that this arbitrary and capricious approach via an undiscussed BSIP in order to enable one person's prediction market coin fantasy is the way to go.

**Comment by pmconrad** [comment]
@happyconcepts A bitasset is not a UIA, the comment you quote is therefore irrelevant to this discussion.

And please tune down your tone a bit if you want to be taken seriously.

**Comment by happyconcepts** [comment]
@pmconrad apparently we have different definitions of "seriously" so would you enlighten me as to  *why* a bitasset is different from a UIA?

Are "smartcoins" that create price feeds for things with no prices to be taken seriously?

**Comment by pmconrad** [comment]
http://docs.bitshares.org/bitshares/user/mpa.html
http://docs.bitshares.org/bitshares/user/uia.html

If a given smartcoin is to be taken seriously lies in the eyes of its users, obviously.

**Comment by happyconcepts** [comment]
Thank you for the clarification.

So it makes sense to me to require an issuer's permission for collateralization.

**Comment by grctest** [comment]
Threw together a draft BSIP:

Title: Introduce 'allow use as bitasset backing collateral' flag/permission to assets
Authors: [Customminer](https://steemit.com/@cm-steem/)
Status: Draft
Type: Protocol
Created: N/A
Discussion:  https://github.com/bitshares/bsips/issues/80
Replaces: N/A
Superseded-By: N/A
Worker: N/A

---

# Abstract

It's currently possible to impose new asset settings through MPA encapsulation without the permission of the backing asset's 'asset owner'.

This BSIP proposes to introduce a new asset permission/flag which enables the asset owner to enable|prevent MPA encapsulation.

# Motivation

By encapsulating an asset (UIA/EBA|MPA) within a new MPA, you can impose new asset settings upon the underlying asset, to the possible detriment of the backing asset's 'asset owner'.

# Rational

By providing asset owners this functionality, we can improve asset owner confidence in the finality of their configured asset settings.

# Specifications

## Create new 'allow use as backing collateral' flag/permission

Rather than create a system of inheriting permissions from backing collateral, a new flag/permission for 'allow use as MPA backing collateral' could simply prevent MPA encapsulation entirely at the discretion of the asset owner.

This flag could only work as long as no MPA has already selected the asset as its backing collateral; setting this as default disabled (not allowed) for newly created assets in the asset creation form could help prevent the asset being used as backing collateral without the user's knowledge.

Existing assets which are currently configured as an bitasset's backing collateral would require this flag to be set default enabled (allowed). This couldn't be changed unless the bitasset reconfigured to an alternative backing collateral - impossible if supply is greater than 0.

Non applicable assets (PM & twice nested MPA) would prevent the flag from being enabled.

Existing assets currently not used as backing collateral could be set to disabled by default.

---

# Discussion

## Consequences of MPA encapsulation

* Removal/Bypassing of market fees (if enabled)
* Re-implementation of confidential transfers (if disabled)
* Evasion of whitelist/blacklist (both user & market lists)
* Preventing the issuer from transfering the asset back to themselves (Can't transfer backing collateral back to yourself)
* Remove backing asset issuer from transfer approval provess.

## Committee configuration

Should all smartcoins be allowed as bitasset backing collateral? Given that XCD already does this with bitUSD, I think it's appropriate. That said, not all committee owned bitassets are in a stable state (bitGOLD for example is in ).

## Enabling the flag grants permisson for all

Currently you can perform MPA encapsulation without involving the asset owner, this could introduce conflict between the two asset owners.

If the flag is enabled, that's an indication that the asset owner accepts any bitasset use case - you wouldn't need to seek explicit permission prior to creating experimental bitassets on the BTS DEX. 

If it's disabled, that's a clear indication that the asset owner doesn't want it used as backing collateral.

## How to configure assets held by null-account?

It's possible that bitassets may be owned by null-account but remain operational, configuring default disabled would burn the possibility of encapsulation - if these assets exist then if possible should be set to enabled?

---

# Summary for Shareholders

* Would likely require a hard fork.
* Introduces new asset owner permissions.
* Helps mitigate negative MPA encapsulation consequences, improving gateway regulatory compliance capability?
* 

# Copyright

This document is placed in the public domain, 100% open source & should be considered MIT licensed.

# See Also

N/A

**Comment by clockworkgr** [comment]
nice job @grctest ...

BTW I agree...a flag to allow or not seems like the best solution

**Comment by pmconrad** [comment]
Yes, good job!

> setting this as default disabled (not allowed) for newly created assets in the asset creation form 

This is not part of the protocol specification but a UI change. Please move this to the "Discussion" section.

Feel free to submit a pull request. You can use number 45 for this BSIP.

**Comment by grctest** [comment]
@pmconrad Made the requested changes & created the pull request: https://github.com/bitshares/bsips/pull/110

**Comment by pmconrad** [comment]
Merged #110 .
Next steps would be to put up for discussion in community forum etc., then ask BBF to put a worker up for voting.
