### ISSUE TITLE
The UI should list TXID

### ISSUE THREAD

**Issue by ebit116** [bitshares/bsips#82]
The txid is useful for me to contact with exchange customer service.So I like to  get the txid easyly in the bitsharesUI .
This is basic service ,I don't think it is need to search cryptofresh.com.
No resistance is our mission。
more detail:Within explore: Add support for searching TXID? #354
https://github.com/bitshares/bitshares-ui/issues/354

**Comment by abitmore** [comment]
I don't think here is the correct place to discuss this feature. Please submit an issue to bitshares-ui repository.
