### ISSUE TITLE
White screen of death

### ISSUE THREAD

**Issue by UnlimitedMiles** [bitshares/bsips#87]
WSOD on:
iPhone 5se iOS 11.4
&
iPhone 5 iOS 11.4.1

Same issue for both Chrome and safari browser on both iOS phones

Screen capture video below:

https://drive.google.com/open?id=1yaFGsTBiiwuAihZg5elFloIwOLIjrjlo

**Comment by svk31** [comment]
This does not belong in "Bitshares Improvement Proposals"...

File it again here: https://github.com/bitshares/bitshares-ui/issues

And please include a description of what you did to trigger the bug, it's hard to tell from the video..
