### ISSUE TITLE
BSIP75: Asset Owner Defines MCR and MSSR Values

### ISSUE THREAD

**Issue by bangzi1001** [bitshares/bsips#96]
MCR (Maintenance Collateral Ratio) & MSSR (Maximum Short Squeeze Ratio) both normally are static and price feed publisher change it when requested by the asset owner. 

Looking that BitCNY MSSR case, why not let the asset owner or committee account have direct control of MCR & MSSR, it will be more efficient for asset owner to test what is the best number MCR & MSSR that are right for their assets. 

(Edited by @abitmore)
A draft is here: https://github.com/bitshares/bsips/pull/218.

**Comment by bitcrab** [comment]
I agree, although I am not sure whether to do this kind change is possible/easy.

in my view, MCR & MSSR of committee created smartcoins are key parameters of the leverage system, change to these parameters need strong consensus of the community, it should not be as dynamic as feed price, in practice, witnesses tend to just keep publishing a fixed value.

**Comment by xeroc** [comment]
The problem here is that market pegged assets can also be **privately owned** and the committee should not have any say about it. That said, the only option left is that the **issuer** is granted permission to change those parameters.

It's great to see a discussion about this.

Anyone has any idea why it is the responsibility of the feed producers to publish the MSSR?

One reason that I can think of is that it allows to have *many* opinions and the blockchain just takes the median.

Another reason might be that the witnesses can act *faster* than the committee can. However, there never was a discussion about how to deal with it and how much they should be allowed to tune the MSSR.

Good to see this finally addressed in discussion ..

**Comment by bitcrab** [comment]
what happened has tell something:

abit has asked witnesses to positively participate in MCR&MSSR determination but get little response.

some witnesses from China just pubulished a different MSSR and then are rapidly voted out. 

all these tell that these parameters are sensitive and need strong consensus, it's not a good way to just let witnesses to publish and adopt the median, they are not very dynamic like feed price, so smartcoin issuer is the right account to manage these parameters.

**Comment by grctest** [comment]
> Another reason might be that the witnesses can act faster than the committee can. However, there never was a discussion about how to deal with it and how much they should be allowed to tune the MSSR.

For private MPA an asset owner could react immediately, but since these values rarely change I don't believe delayed action via committee consensus would be an issue.

I think it's a good idea for these values to be set by the asset owner, also the docs should elaborate with scenarios where different values would be needed & the impact of such change on MPA operation.

Price feed script repos would need updated to not handle the MCR/MSSR values - some extra maintenance to notify private MPA owners of.

**Comment by abitmore** [comment]
I think technically it's doable. Asset owner has the final say on who can publish feeds anyway.

> The problem here is that market pegged assets can also be privately owned and the committee should not have any say about it. That said, the only option left is that the issuer is granted permission to change those parameters.

In the core we can add a field or two in asset info to indicate whether to ignore MCR and/or MSSR published by feed producers.

**Comment by xeroc** [comment]
I think this change can be beneficial for BitShares in general.

**Comment by jonnybitcoin** [comment]
I agree smartcoin issuers should set MCR as a permission it is created.  With the permission on or off to make it unchangable after it's creation.

**Comment by clockworkgr** [comment]
I think these parameters are very much market dependent and SHOULD be fed by witnesses same as with prices. Taking BSIP42 as a recent example, a similar result could have been achieved by keeping feed price calculated the same way as before (and thus for all intents and purposes "fair") and changing/optimising MCR instead.

That being said, I don't think witnesses (including me) have the required economics knowledge to set them appropriately so I'm kinda divided on what the best course of action is.

**Comment by shulthz** [comment]
I think the asset owner can set the Margin Call Ratio.

Seperate the Margin Call Ratio and the Maintenance collateral ratio.

e.g. if the Maintenance collateral ratio is 1.75,  system can set the basic Margin Call Ratio to 1.6, and the asset owner can set his Margin Call Ratio from 1.6 to 1.35.  

When the price drop down 8.5%,  the margin call could only happen at 1.6, as the Market Rebounds always, this provides the market with a large buffer as prices fall again.

**Comment by pmconrad** [comment]
> Seperate the Margin Call Ratio and the Maintenance collateral ratio.

Sorry, I can't follow you there. Please explain what you mean with "Margin Call Ratio" and "Maintenance Collateral Ratio".

**Comment by shulthz** [comment]
> > Seperate the Margin Call Ratio and the Maintenance collateral ratio.
> 
> Sorry, I can't follow you there. Please explain what you mean with "Margin Call Ratio" and "Maintenance Collateral Ratio".

now we only have one ratio 'Maintenance collateral ratio', the CR below the Maintenance collateral ratio, the debit will be margin called.

so we can creat a ' Margin Call Ratio ', the CR below the Margin Call Ratio  will  be margin called.

e.g.  Maintenance collateral ratio=1.75
         Margin call ratio=1.6
the CR at 1.75-1.6 will not be margin called,  when the CR below 1.6,  the margin call will happen.

**Comment by pmconrad** [comment]
How is that different from changing what we currently call MCR to 1.6? What would be the future purpose of the "Maintenance CR"?

**Comment by shulthz** [comment]
> How is that different from changing what we currently call MCR to 1.6? What would be the future purpose of the "Maintenance CR"?

We call MCR to 1.60 is what you say the "Maintenance CR", People can make their CR to 1.6.

The Margin call ratio mean: 
if the Maintenance CR is 1.75,  the margin call ratio is 1.6, people can't make their CR to 1.6, only can make their CR to 1.75.   When their CR below 1.6, they will be margin called.

We can set a range of the margin call ratio from 1.6 to 1.35, people can change their margin call ratio from 1.6 to 1.35 as they wish.

**Comment by pmconrad** [comment]
I see, thanks for the explanation.

**Comment by bangzi1001** [comment]
Now committee control assets just work like "MCR & MSSR Set By Asset Owner":

1. Committee members write a BSIP or Worker Proposal Poll to adjust MCR and MSSR.
2. Voters/Proxies vote to support or against the adjustment. 
3. If the  BSIP or Worker Proposal Voted in and more votes than those who against it, witnesses will implement the adjustment in their price feed.

https://github.com/bitshares/bsips/issues/97
https://github.com/bitshares/bsips/issues/140

**Comment by ryanRfox** [comment]
I feel the discussion here and in #216 lend toward drafting a BSIP at this time. I have assigned BSIP75. Looking for someone to draft the document following this template https://github.com/bitshares/bsips/blob/master/BSIPs-Template.md

**Comment by jmjatlanta** [comment]
I will volunteer, and am happy to take on partners.

**Comment by jmjatlanta** [comment]
Q: I would like the opinions of others as to whether 1 switch controls where to get both of these values, or if we need 2 switches (one for MCR and one for MSSR).

I realize that 2 switches adds flexibility, but is it needless complexity? Would an asset creator ever want to be in control of 1, but have price feeds control the other?

**Comment by abitmore** [comment]
My own opinion is one switch.

**Comment by jmjatlanta** [comment]
I heard from a few others that two switches were better. BSIP updated. I still welcome more input/opinions, of course.

**Comment by froooze** [comment]
> Seperate the Margin Call Ratio and the Maintenance collateral ratio.

YES, or short just `CCR` (call CR) and `MCR`. The higher `MCR` limits bad debt and the lower `CCR` limits margin calls.

**Comment by abitmore** [comment]
@froooze that's BSIP77 (#161, #226).

**Comment by froooze** [comment]
@abitmore @jmjatlanta 
yes and we have now three values here and not two like in the start post:
- `MSSR`
- `MCR`
- `CCR`

**Comment by abitmore** [comment]
@froooze IMHO `ICR` is designed as an asset option in the first place, but not be able to be updated by feed producers, so no need to discuss it in this BSIP.

**Comment by froooze** [comment]
@abitmore 
When feed-producer can update `MCR` they should also be able to update `ICR`, because `ICR` is also part of `MCR`. Everything else is not consequent!

**Comment by froooze** [comment]
@abitmore 
Why? `ICR` is more important than `MCR`, because it is now the limiting factor how much someone can borrow from blockchain! Before introducing `ICR`, this was done by `MCR`.

**Comment by froooze** [comment]
> Because the parameter should be decided by asset owners.

When `ICR` should set by asset owner, we need to include `ICR` in this proposal.

**Comment by abitmore** [comment]
Done: https://github.com/bitshares/bsips/pull/218.
