### ISSUE TITLE
BSIP41: Reduce MSSR of bitCNY from 1.1 to 1.05

### ISSUE THREAD

**Issue by bitcrab** [bitshares/bsips#97]
BSIP: 
Title: Reduce MSSR of bitCNY from 1.1 to 1.05
Authors: Jerry Liu <bitcrab@qq.com>
Status: Draft
Type: Protocol
Created: 2018-08-17
Discussion: https://bitsharestalk.org/index.php?topic=26928.0
Worker: no

### **Abstract**
We here propose to reduce the Maximum short squeeze ratio (MSSR) of bitCNY from 1.1 to 1.05, to lower the shorting incentive.

### **Motivation**
Bitshares is a financial system with leverage, here in the traders there are BTS longers and shorters, surely the traders are finding their chance to make profit in trading, if shorters can always find chance to make big profit by shorting BTS, that’s not a good news to BTS ecosystem, from the perspective of the whole BTS ecosystem consisted of DEX and smartcoin, we need to review the rules continually, while guaranteeing fairness and the risks always be released in time, we also need to try optimize the rules to encourage BTS longers, to provide enough incentive to make BTS ecosystem to grow up.

  
### **Rationale**
Currently there are 2 key smartcoin parameters which are maintained by witnesses, they are MCR(Maintenance collateral ratio ) and MSSR(Maximum short squeeze ratio) , now MCR=1.75 and MSSR=1.1.

When a debt position is margin called, the placed sell orders is at price feed price/MSSR, so MSSR determine the discount of collateral force selling the higher MSSR, the bigger the discount.

So high MSSR benefits the filling of margin call sell orders and help to release risks rapidly, however at the same time, high MSSR means buying margin call orders is with big discount, so it encourage BTS shorters to accumulate smartcoins and wait or even try to make margin call happen and get cheaper collateral. This does not do good to the ecosystem grow up.

We need to release risks rapidly while margin call happen, we also need to try to lower the shorting incentive, so we need a balance, what a MSSR is appropriate depend on the liquidity of the market and also some other factors.

bitCNY have a very good liquidity, BTS/bitCNY pair in DEX is the pair with highest BTS volume on the earth, after in 19th July the hard fork activated the target CR feature, the sell pressure comes from margin called orders decreased greatly,  we are sure that the for bitCNY black swan has very very little chance to happen, it’s the time to reduce MSSR to push bitCNY ecosysm move forward. 

### **Specification**
witnesses adjust the MSSR from 1.1 to 1.05 while publishing feed price.
Discussion
Will this change be implemented to bitUSD and other smartcoins?
this time No, bitUSD and other smartcoins has a much lower liquidity than bitCNY, a high MSSR need to be kept to guarantee the rapid settlement of margin called dept positions.
How to make sure a strong consensus is reached?
China community has discussed about this change for years, however, target CR feature + good bitCNY liquidity make current time the good time to do the change, in the forum thread, about 70% of the voters support this change, if necessary, a opinion survey worker proposal will be created to collect stake based opinion.
As MSSR comes from witness publishing, so when BTS community reach a strong consensus to do the change, we need witnesses to apply the change based on the community consensus 

### **Summary for Shareholders**
Reduce shorting incentive while guaranteeing fairness and safe is an important logic for the ecosystem to evolve.

### **Copyright**
This document is placed in the public domain.

**Comment by abitmore** [comment]
Created PR #98 for this issue.

**Comment by abitmore** [comment]
Closing since PR #98 has been merged.
